config/routes.rb
DavisSite::Application.routes.draw do
  resources :movers

  devise_for :drivers

  root 'welcome#index'

end

app/models/driver.rb
class Driver < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/mover.rb
class Mover < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movers_controller.rb
class MoversController < ApplicationController
  before_action :set_mover, only: [:show, :edit, :update, :destroy]

  # GET /movers
  # GET /movers.json
  def index
    @movers = Mover.all

  end

  # GET /movers/1
  # GET /movers/1.json
  def show
  end

  # GET /movers/new
  def new
    @mover = Mover.new
  end

  # GET /movers/1/edit
  def edit
  end

  # POST /movers
  # POST /movers.json
  def create
    @mover = Mover.new(mover_params)

    respond_to do |format|
      if @mover.save
        format.html { redirect_to @mover, notice: 'Mover was successfully created.' }
        format.json { render action: 'show', status: :created, location: @mover }
      else
        format.html { render action: 'new' }
        format.json { render json: @mover.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movers/1
  # PATCH/PUT /movers/1.json
  def update
    respond_to do |format|
      if @mover.update(mover_params)
        format.html { redirect_to @mover, notice: 'Mover was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @mover.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movers/1
  # DELETE /movers/1.json
  def destroy
    @mover.destroy
    respond_to do |format|
      format.html { redirect_to movers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mover
      @mover = Mover.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mover_params
      params.require(:mover).permit(:name, :distance, :estimated_time, :move_time, :description)
    end
end

 

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
		@mover = Mover.new
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movers_helper.rb
module MoversHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class=<%= yield (:background_class) %> lang="en">
<head>
  <title>DavisSite</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Dosis:400,200,600' rel='stylesheet' type='text/css'>

   

    <title><%= yield (:title) %> | Haulla</title>

    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.css" rel="stylesheet">

    <!-- Custom CSS for the 'Full' Template -->
    <link href="css/the-big-picture.css" rel="stylesheet">
</head>


    <nav class="navbar navbar-fixed-bottom navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.php">Haulla</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="#about">How it Works</a>
                    </li>
                    
                    <li><a href="#contact">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>




<% if notice %>
		<p class="notice alert-warning"><%= notice %></p>

     <% end %>
    <% if alert %>
		<p class="alert alert-success"><%= alert %></p>
	<% end %>

<%= yield %>




    <!-- JavaScript -->
    <script src="js/jquery-1.10.2.js"></script>
    <script src="js/bootstrap.js"></script>

</body>
</html>


<!-- The full page image background will only work if the html has the custom class set to it! Don't delete it! -->

app/views/movers/_form.html.erb
<%= form_for(@mover) do |f| %>
  <% if @mover.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mover.errors.count, "error") %> prohibited this mover from being saved:</h2>

      <ul>
      <% @mover.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movers/edit.html.erb
<h1>Editing mover</h1>

<%= render 'form' %>

<%= link_to 'Show', @mover %> |
<%= link_to 'Back', movers_path %>

app/views/movers/index.html.erb
<h1>Listing movers</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @movers.each do |mover| %>
      <tr>
        <td><%= link_to 'Show', mover %></td>
        <td><%= link_to 'Edit', edit_mover_path(mover) %></td>
        <td><%= link_to 'Destroy', mover, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mover', new_mover_path %>

app/views/movers/new.html.erb
<h1>New mover</h1>

<%= render 'form' %>

<%= link_to 'Back', movers_path %>

app/views/movers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_mover_path(@mover) %> |
<%= link_to 'Back', movers_path %>

app/views/welcome/_mover.html.erb
<%= form_for @mover do |f| %>
  <% if @mover.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mover.errors.count, "error") %> prohibited this mover from being saved:</h2>

      <ul>
      <% @mover.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.text_field :name, :placeholder => "Full Name" %><br>

  <%= f.label :estimated_time %>
  <%= f.select :estimated_time, [1,2,3,4,5, 6] %><%= " hours" %><br>

  <%= f.telephone_field :phone, :placeholder => "e.g. (858) 449 4180" %><br>

  <%= f.label :move_time, "When you trying to move" %>
  <%= f.datetime_select :move_time %><br>

  <%= f.label :distance, "Estimated Distance" %>
  <%= f.number_field :distance, :placeholder => "e.g. 1.5, 5" %><%= " miles" %><br>

  <%= f.text_area :description, :placeholder => "Job Desciption" %><br>

  <div class="actions">
    <%= f.submit :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<%= content_for :background_class, "full" %>

<!-- The full page image background will only work if the html has the custom class set to it! Don't delete it! -->


<body>


    <nav class="navbar navbar-fixed-bottom navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.php">Haulla</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="#about">How it Works</a>
                    </li>
                    
                    <li><a href="#contact">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-xs-12 white-bg">
                <h1>Have a Truck?</h1>
                <%= link_to "Sign Up/Sign In", new_driver_registration_path, :class => "btn btn-primary btn-lg"  %>
            </div>
            <div class="col-sm-6 col-xs-12 white-bg">
                <h1>Need a Truck?</h1>
                <%= render "mover" %>
            </div>
            
        </div>
    </div>


    <!-- JavaScript -->
    <script src="js/jquery-1.10.2.js"></script>
    <script src="js/bootstrap.js"></script>

</body>

</html>